export const KEY_CODES = {
  ARROW_UP: "ArrowUp",
  ARROW_LEFT: "ArrowLeft",
  ARROW_DOWN: "ArrowDown",
  ARROW_RIGHT: "ArrowRight",
  SPACE: "Space",
  W: "KeyW",
  A: "KeyA",
  S: "KeyS",
  D: "KeyD",
  Digit0: 'Digit0',
  Digit1: 'Digit1',
  Digit2: 'Digit2',
  Digit3: 'Digit3',
  Digit4: 'Digit4',
  Digit5: 'Digit5',
  Digit6: 'Digit6',
  Digit7: 'Digit7',
  Digit8: 'Digit8',
  Digit9: 'Digit9',
};
